name: CI

on:
  push:
    branches: [ master, development_ci ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
   Spec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        check: [test]
        ruby_version: [2.4.10, 2.5.8, 2.7.2]
        puppet_gem_version: [~> 5.0, ~> 6.0, ~> 7.0]
        exclude:
        - ruby_version: 2.4.10
          puppet_gem_version: [~> 6.0, ~> 7.0]
        - ruby_version: 2.5.8
          puppet_gem_version: [~> 5.0, ~> 7.0]
        - ruby_version: 2.7.2
          puppet_gem_version: [~> 5.0, ~> 6.0]
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby_version}}
    - name: Spec Tests
      uses: puppetlabs/action-litmus_spec@master
      with:
        puppet_gem_version: ${{ matrix.puppet_gem_version }}
        check: ${{ matrix.check }}
